#!/bin/bash

# SLRUM job script

echo "Job ID: $SLURM_JOB_ID"

module purge

module load Python/3.10.4-GCCcore-11.3.0
module load cuDNN/8.4.1.50-CUDA-11.7.0

DIRNAME="$(basename "$(pwd)")"

cp -pR $PWD $PFSDIR/
cd $PFSDIR/$DIRNAME

make switch-env hpc
make env-local
make test
make check

## Install all dependencies available in requirements.txt
# make pia
# Run Makefile targets
# make hpc-run

# Install dependencies 
# make piu numpy matplotlib

# Install dependencies for GPU
make hpc-gpu-deps
make hpc-gpu-run