#!/bin/bash

SRC='pkg'

echo "You are about to commit" $(git diff --cached --name-only --diff-filter=ACM)
echo "to" $(git branch --show-current)

isort $SRC

black $SRC

pylint --rcfile .pylintrc.dev $SRC

mypy

